//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpreGest.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.DetallePedido = new HashSet<DetallePedido>();
            this.ProductoRecibir = new HashSet<ProductoRecibir>();
        }
    
        public int idProducto { get; set; }
        public int idCategoria { get; set; }
        public string descripcion { get; set; }
        public int unidadesStock { get; set; }
        public int unidadesPedidas { get; set; }
        public int unidadesReservadas { get; set; }
        public int stockMinimo { get; set; }
        public bool reponer { get; set; }
        public int beneficio { get; set; }
        public Nullable<decimal> precioCompraUnitario { get; set; }
        public Nullable<decimal> precioVentaUnitario { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePedido> DetallePedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoRecibir> ProductoRecibir { get; set; }
    }
}
